/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const SigninLazyRouteImport = createFileRoute('/signin')()
const IndexLazyRouteImport = createFileRoute('/')()
const BreaksBreakSlugLazyRouteImport = createFileRoute('/breaks/$breakSlug')()

const SigninLazyRoute = SigninLazyRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/signin.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const BreaksBreakSlugLazyRoute = BreaksBreakSlugLazyRouteImport.update({
  id: '/breaks/$breakSlug',
  path: '/breaks/$breakSlug',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/breaks.$breakSlug.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/signin': typeof SigninLazyRoute
  '/breaks/$breakSlug': typeof BreaksBreakSlugLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/signin': typeof SigninLazyRoute
  '/breaks/$breakSlug': typeof BreaksBreakSlugLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/signin': typeof SigninLazyRoute
  '/breaks/$breakSlug': typeof BreaksBreakSlugLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/signin' | '/breaks/$breakSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/signin' | '/breaks/$breakSlug'
  id: '__root__' | '/' | '/signin' | '/breaks/$breakSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  SigninLazyRoute: typeof SigninLazyRoute
  BreaksBreakSlugLazyRoute: typeof BreaksBreakSlugLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breaks/$breakSlug': {
      id: '/breaks/$breakSlug'
      path: '/breaks/$breakSlug'
      fullPath: '/breaks/$breakSlug'
      preLoaderRoute: typeof BreaksBreakSlugLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  SigninLazyRoute: SigninLazyRoute,
  BreaksBreakSlugLazyRoute: BreaksBreakSlugLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
