/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const SigninLazyRouteImport = createFileRoute('/signin')()
const BreaksLazyRouteImport = createFileRoute('/breaks')()
const IndexLazyRouteImport = createFileRoute('/')()
const BreaksBreakSlugLazyRouteImport = createFileRoute('/breaks/$breakSlug')()

const SigninLazyRoute = SigninLazyRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/signin.lazy').then((d) => d.Route))
const BreaksLazyRoute = BreaksLazyRouteImport.update({
  id: '/breaks',
  path: '/breaks',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/breaks.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const BreaksBreakSlugLazyRoute = BreaksBreakSlugLazyRouteImport.update({
  id: '/$breakSlug',
  path: '/$breakSlug',
  getParentRoute: () => BreaksLazyRoute,
} as any).lazy(() =>
  import('./routes/breaks.$breakSlug.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/breaks': typeof BreaksLazyRouteWithChildren
  '/signin': typeof SigninLazyRoute
  '/breaks/$breakSlug': typeof BreaksBreakSlugLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/breaks': typeof BreaksLazyRouteWithChildren
  '/signin': typeof SigninLazyRoute
  '/breaks/$breakSlug': typeof BreaksBreakSlugLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/breaks': typeof BreaksLazyRouteWithChildren
  '/signin': typeof SigninLazyRoute
  '/breaks/$breakSlug': typeof BreaksBreakSlugLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/breaks' | '/signin' | '/breaks/$breakSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/breaks' | '/signin' | '/breaks/$breakSlug'
  id: '__root__' | '/' | '/breaks' | '/signin' | '/breaks/$breakSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  BreaksLazyRoute: typeof BreaksLazyRouteWithChildren
  SigninLazyRoute: typeof SigninLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breaks': {
      id: '/breaks'
      path: '/breaks'
      fullPath: '/breaks'
      preLoaderRoute: typeof BreaksLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breaks/$breakSlug': {
      id: '/breaks/$breakSlug'
      path: '/$breakSlug'
      fullPath: '/breaks/$breakSlug'
      preLoaderRoute: typeof BreaksBreakSlugLazyRouteImport
      parentRoute: typeof BreaksLazyRoute
    }
  }
}

interface BreaksLazyRouteChildren {
  BreaksBreakSlugLazyRoute: typeof BreaksBreakSlugLazyRoute
}

const BreaksLazyRouteChildren: BreaksLazyRouteChildren = {
  BreaksBreakSlugLazyRoute: BreaksBreakSlugLazyRoute,
}

const BreaksLazyRouteWithChildren = BreaksLazyRoute._addFileChildren(
  BreaksLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  BreaksLazyRoute: BreaksLazyRouteWithChildren,
  SigninLazyRoute: SigninLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
